# The files are generated into the path specified by `arb-dir`
arb-dir: l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
untranslated-messages-file : untranslated_messages.json
synthetic-package: false
output-dir: lib/generated/i18n